version: '3.7'

services:
  php-apache:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "80:80"
    volumes:
      - .:/var/www/html
    environment:
      - HOST=postgres
      - PORT=5432
      - DBNAME=${DBNAME}
      - USER=${USERNAME}
      - PASSWORD=${PASSWORD}
    depends_on:
      - postgres
    extra_hosts:
      - "host.docker.internal:host-gateway"

  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: ${USERNAME}     
      POSTGRES_PASSWORD: ${PASSWORD} 
      POSTGRES_DB: ${DBNAME}         
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "${USERNAME}", "-d", "${DBNAME}"]
      interval: 10s
      retries: 5
      start_period: 5s
      timeout: 5s
  