services:
  php-apache:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "80:80"
    volumes:
      - .:/var/www/html
    environment:
      - HOST=${HOST}           
      - PORT=${PORT}           
      - DBNAME=${DBNAME}       
      - USER=${USERNAME}       
      - PASSWORD=${PASSWORD}   
    depends_on:
      - postgres

  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: ${USERNAME}     
      POSTGRES_PASSWORD: ${PASSWORD} 
      POSTGRES_DB: ${DBNAME}         
    ports:
      - "5432:5432"